(()=>{
'use strict';
const KEY='planuf-budget-builder-v3';
const D=window.PLANUF_DATA||{equipment:[],productionTemplates:[],crewRoles:[],defaults:{}};
const app=document.getElementById('app');
const £=v=>new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP',maximumFractionDigits:0}).format(Number(v||0));
const n=v=>{v=Number(v);return Number.isFinite(v)?v:0};
const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const tpl=id=>D.productionTemplates.find(t=>t.id===id)||D.productionTemplates[0]||{};
const shootDays=(eps,cap)=>Math.max(1,Math.ceil(Math.max(1,n(eps))/Math.max(1,n(cap))));
const editDays=(eps,per)=>Math.max(0,Math.ceil(Math.max(0,n(eps))*Math.max(0,n(per))));
const makeEquip=()=>D.equipment.map((x,i)=>({id:'eq'+i,category:x.category,item:x.item,qty:x.qty,unit:x.unit,url:x.url,decision:x.owned?'owned':'buy'}));
const makeCrew=()=>D.crewRoles.map(x=>({id:x.id,role:x.role,qty:x.qty,rate:x.rate,phase:x.phase,enabled:!!x.enabled}));
function fresh(){const t=tpl('one-shot'),e=t.episodes||1,cap=t.episodesPerShootDay||6,ed=t.editDaysPerEpisode||1;return{tab:'setup',projectName:'Untitled Planuf Production',productionType:t.id||'one-shot',episodes:e,episodesPerShootDay:cap,editDaysPerEpisode:ed,shootLocked:false,editLocked:false,manualShootDays:shootDays(e,cap),manualEditDays:editDays(e,ed),locationHirePerDay:D.defaults.locationHirePerDay||250,castCostPerEpisode:D.defaults.castCostPerEpisode||20,contingencyPercent:D.defaults.contingencyPercent||10,crew:makeCrew(),equipment:makeEquip()}}
function load(){try{let s=JSON.parse(localStorage.getItem(KEY));if(!s)return fresh();let f=fresh();s=Object.assign(f,s);s.crew=makeCrew().map(r=>Object.assign(r,(s.crew||[]).find(x=>x.id===r.id)||{}));s.equipment=(s.equipment&&s.equipment.length)?s.equipment:f.equipment;return s}catch(e){return fresh()}}
let S=load();
const save=()=>localStorage.setItem(KEY,JSON.stringify(S));
function sched(){let cs=shootDays(S.episodes,S.episodesPerShootDay),ce=editDays(S.episodes,S.editDaysPerEpisode);return{shoot:S.shootLocked?Math.max(1,n(S.manualShootDays)):cs,edit:S.editLocked?Math.max(0,n(S.manualEditDays)):ce,calcShoot:cs,calcEdit:ce}}
function calc(){let sc=sched();let crew=S.crew.filter(r=>r.enabled).map(r=>{let mult=r.phase==='edit'?sc.edit:r.phase==='episode'?n(S.episodes):sc.shoot;return Object.assign({},r,{mult,total:n(r.qty)*n(r.rate)*mult})});let prod={crew:crew.reduce((a,x)=>a+x.total,0),location:sc.shoot*n(S.locationHirePerDay),cast:n(S.episodes)*n(S.castCostPerEpisode)};prod.subtotal=prod.crew+prod.location+prod.cast;let equip=S.equipment.reduce((a,x)=>a+(x.decision==='buy'?n(x.qty)*n(x.unit):0),0);let cont=Math.round((prod.subtotal+equip)*(n(S.contingencyPercent)/100));return{sc,crew,prod,equip,cont,total:prod.subtotal+equip+cont}}
function set(k,v){S[k]=v;if(k==='episodes'||k==='episodesPerShootDay')S.manualShootDays=shootDays(S.episodes,S.episodesPerShootDay);if(k==='episodes'||k==='editDaysPerEpisode')S.manualEditDays=editDays(S.episodes,S.editDaysPerEpisode);save();render()}
function useTemplate(id){let t=tpl(id);S.productionType=id;S.episodes=t.episodes||S.episodes;S.episodesPerShootDay=t.episodesPerShootDay||S.episodesPerShootDay;S.editDaysPerEpisode=t.editDaysPerEpisode||S.editDaysPerEpisode;S.shootLocked=false;S.editLocked=false;S.manualShootDays=shootDays(S.episodes,S.episodesPerShootDay);S.manualEditDays=editDays(S.episodes,S.editDaysPerEpisode);save();render()}
const decision=x=>[['owned','Already owned'],['buy','Need to buy'],['hire','Hire / borrow'],['company','Company decision']].map(o=>`<option value="${o[0]}" ${x===o[0]?'selected':''}>${o[1]}</option>`).join('');
const phase=x=>[['shoot','Shoot day'],['edit','Edit day'],['episode','Episode']].map(o=>`<option value="${o[0]}" ${x===o[0]?'selected':''}>${o[1]}</option>`).join('');
const stat=x=>x==='owned'?'status-owned':x==='hire'?'status-hire':x==='company'?'status-company':'status-buy';
const lab=x=>x==='owned'?'Already owned':x==='hire'?'Hire / borrow':x==='company'?'Company decision':'Need to buy';
const tabs=()=>['setup','crew','equipment','summary'].map((t,i)=>`<button class="tab ${S.tab===t?'active':''}" data-tab="${t}">${i+1}. ${t[0].toUpperCase()+t.slice(1)}</button>`).join('');
const list=(rows,money)=>`<ul class="summary-list">${rows.map(r=>`<li><span>${r[0]}</span><strong>${money?£(r[1]):r[1]}</strong></li>`).join('')}</ul>`;
function render(){let C=calc();app.innerHTML=`<section class="hero"><div><p class="eyebrow">Planuf Productions</p><h1>Budget Builder</h1><p class="subhead">Automated production budget: episode count drives shoot days; crew roles drive labour cost; only buy-now equipment is charged.</p></div><aside class="total-card"><p class="total-label">Current required spend</p><p class="total-value">${£(C.total)}</p><p class="total-note">${S.episodes} episodes · ${C.sc.shoot} shoot days · ${C.sc.edit} edit days</p></aside></section><nav class="tabs">${tabs()}</nav>${S.tab==='setup'?setup(C):''}${S.tab==='crew'?crew(C):''}${S.tab==='equipment'?equipment(C):''}${S.tab==='summary'?summary(C):''}`;bind()}
function setup(C){return`<section class="grid"><div class="panel"><h2>Production setup</h2><p class="note">This is now rule-based. 15 episodes at 6 episodes per shoot day automatically becomes 3 shoot days.</p><div class="form-grid"><label>Project name<input data-field="projectName" value="${esc(S.projectName)}"></label><label>Production shape<select data-template>${D.productionTemplates.map(t=>`<option value="${t.id}" ${t.id===S.productionType?'selected':''}>${t.name}</option>`).join('')}</select></label><label>Episodes<input type="number" min="1" data-num="episodes" value="${S.episodes}"></label><label>Episodes possible per shoot day<input type="number" min="1" data-num="episodesPerShootDay" value="${S.episodesPerShootDay}"></label><label>Shoot days<input type="number" min="1" data-manual-shoot value="${C.sc.shoot}" ${S.shootLocked?'':'disabled'}></label><label>Edit days per episode<input type="number" min="0" step="0.25" data-num="editDaysPerEpisode" value="${S.editDaysPerEpisode}"></label><label>Edit days<input type="number" min="0" data-manual-edit value="${C.sc.edit}" ${S.editLocked?'':'disabled'}></label><label>Location hire per shoot day<input type="number" min="0" data-num="locationHirePerDay" value="${S.locationHirePerDay}"></label><label>Cast/contributor cost per episode<input type="number" min="0" data-num="castCostPerEpisode" value="${S.castCostPerEpisode}"></label><label>Contingency %<input type="number" min="0" data-num="contingencyPercent" value="${S.contingencyPercent}"></label></div><div class="actions"><button data-toggle-shoot>${S.shootLocked?'Use automatic shoot days':'Override shoot days'}</button><button data-toggle-edit>${S.editLocked?'Use automatic edit days':'Override edit days'}</button><button data-tab="crew">Continue to Crew</button><button class="secondary" data-reset>Reset local draft</button></div></div><aside class="panel"><h2>Automation check</h2>${list([['Episodes',S.episodes],['Episodes per shoot day',S.episodesPerShootDay],['Calculated shoot days',C.sc.calcShoot],['Active shoot days',C.sc.shoot],['Calculated edit days',C.sc.calcEdit],['Active edit days',C.sc.edit]],false)}<p class="note">Formula: episodes divided by capacity per shoot day, rounded up.</p></aside></section>`}
function crew(C){return`<section class="panel"><h2>Crew and labour</h2><p class="note">Shoot roles multiply by shoot days. Edit roles multiply by edit days. Episode roles multiply by episode count.</p><div class="table-wrap"><table><thead><tr><th>Use</th><th>Role</th><th>Qty</th><th>Rate</th><th>Charged by</th><th>Multiplier</th><th>Total</th></tr></thead><tbody>${S.crew.map(r=>crewRow(r,C)).join('')}</tbody></table></div><div class="mobile-card-list">${S.crew.map(r=>crewCard(r,C)).join('')}</div><div class="actions"><button data-tab="equipment">Continue to Equipment</button><button class="secondary" data-tab="setup">Back to Setup</button></div></section>`}
function crewRow(r,C){let l=C.crew.find(x=>x.id===r.id);return`<tr><td><select data-crew="${r.id}" data-key="enabled"><option value="true" ${r.enabled?'selected':''}>Use</option><option value="false" ${!r.enabled?'selected':''}>Off</option></select></td><td>${esc(r.role)}</td><td><input type="number" min="0" value="${r.qty}" data-crew="${r.id}" data-key="qty"></td><td><input type="number" min="0" value="${r.rate}" data-crew="${r.id}" data-key="rate"></td><td><select data-crew="${r.id}" data-key="phase">${phase(r.phase)}</select></td><td>${l?l.mult:0}</td><td>${£(l?l.total:0)}</td></tr>`}
function crewCard(r,C){let l=C.crew.find(x=>x.id===r.id);return`<article class="equipment-card"><strong>${esc(r.role)}</strong><div class="mini">Multiplier ${l?l.mult:0} · Total ${£(l?l.total:0)}</div><label>Use<select data-crew="${r.id}" data-key="enabled"><option value="true" ${r.enabled?'selected':''}>Use</option><option value="false" ${!r.enabled?'selected':''}>Off</option></select></label><div class="card-controls"><label>Qty<input type="number" min="0" value="${r.qty}" data-crew="${r.id}" data-key="qty"></label><label>Rate £<input type="number" min="0" value="${r.rate}" data-crew="${r.id}" data-key="rate"></label></div><label>Charged by<select data-crew="${r.id}" data-key="phase">${phase(r.phase)}</select></label></article>`}
function equipment(C){return`<section class="panel"><h2>Equipment reconciliation</h2><p class="note">Only items marked “Need to buy” are added to the spend.</p><div class="table-wrap"><table><thead><tr><th>Category</th><th>Item</th><th>Qty</th><th>Unit</th><th>Status</th><th>Total</th><th>Link</th></tr></thead><tbody>${S.equipment.map(eqRow).join('')}</tbody></table></div><div class="mobile-card-list">${S.equipment.map(eqCard).join('')}</div><div class="actions"><button data-tab="summary">Continue to Summary</button><button class="secondary" data-tab="crew">Back to Crew</button></div></section>`}
function eqRow(r){return`<tr><td>${esc(r.category)}</td><td>${esc(r.item)}</td><td><input type="number" min="0" value="${r.qty}" data-eq="${r.id}" data-key="qty"></td><td><input type="number" min="0" value="${r.unit}" data-eq="${r.id}" data-key="unit"></td><td><select data-eq="${r.id}" data-key="decision">${decision(r.decision)}</select><br><span class="status-pill ${stat(r.decision)}">${lab(r.decision)}</span></td><td>${£(n(r.qty)*n(r.unit))}</td><td><a href="${r.url}" target="_blank" rel="noopener">Buy link</a></td></tr>`}
function eqCard(r){return`<article class="equipment-card"><strong>${esc(r.item)}</strong><div class="mini">${esc(r.category)} · ${£(n(r.qty)*n(r.unit))}</div><div class="card-controls"><label>Qty<input type="number" min="0" value="${r.qty}" data-eq="${r.id}" data-key="qty"></label><label>Unit £<input type="number" min="0" value="${r.unit}" data-eq="${r.id}" data-key="unit"></label></div><label>Status<select data-eq="${r.id}" data-key="decision">${decision(r.decision)}</select></label><p><span class="status-pill ${stat(r.decision)}">${lab(r.decision)}</span></p><a href="${r.url}" target="_blank" rel="noopener">Open buying link</a></article>`}
function summary(C){let buys=S.equipment.filter(x=>x.decision==='buy');return`<section class="grid"><div class="panel"><h2>Budget summary</h2><p><strong>${esc(S.projectName)}</strong></p>${list([['Episodes',S.episodes],['Shoot days',C.sc.shoot],['Edit days',C.sc.edit]],false)}${list([['Crew and labour',C.prod.crew],['Location hire',C.prod.location],['Cast / contributors',C.prod.cast],['Production subtotal',C.prod.subtotal],['Equipment to buy now',C.equip],['Contingency',C.cont],['Total required spend',C.total]],true)}<div class="actions"><button data-copy>Copy summary</button><button class="secondary" data-tab="equipment">Back to Equipment</button></div></div><aside class="panel"><h2>Need to buy now</h2>${buys.length?`<ul class="summary-list">${buys.map(x=>`<li><span>${esc(x.item)} × ${x.qty}</span><strong>${£(n(x.qty)*n(x.unit))}</strong></li>`).join('')}</ul>`:'<p class="note">Nothing is marked as “Need to buy” at the moment.</p>'}</aside></section>`}
function bind(){app.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{S.tab=b.dataset.tab;save();render()});app.querySelectorAll('[data-field]').forEach(i=>i.onchange=()=>set(i.dataset.field,i.value));app.querySelectorAll('[data-num]').forEach(i=>i.onchange=()=>set(i.dataset.num,n(i.value)));app.querySelectorAll('[data-template]').forEach(i=>i.onchange=()=>useTemplate(i.value));app.querySelectorAll('[data-eq]').forEach(i=>i.onchange=()=>{let r=S.equipment.find(x=>x.id===i.dataset.eq);if(r)r[i.dataset.key]=(i.dataset.key==='qty'||i.dataset.key==='unit')?n(i.value):i.value;save();render()});app.querySelectorAll('[data-crew]').forEach(i=>i.onchange=()=>{let r=S.crew.find(x=>x.id===i.dataset.crew);if(r)r[i.dataset.key]=i.dataset.key==='enabled'?i.value==='true':(i.dataset.key==='qty'||i.dataset.key==='rate')?n(i.value):i.value;save();render()});let ms=app.querySelector('[data-manual-shoot]');if(ms)ms.onchange=()=>{S.manualShootDays=n(ms.value);save();render()};let me=app.querySelector('[data-manual-edit]');if(me)me.onchange=()=>{S.manualEditDays=n(me.value);save();render()};let ts=app.querySelector('[data-toggle-shoot]');if(ts)ts.onclick=()=>{S.shootLocked=!S.shootLocked;if(!S.shootLocked)S.manualShootDays=shootDays(S.episodes,S.episodesPerShootDay);save();render()};let te=app.querySelector('[data-toggle-edit]');if(te)te.onclick=()=>{S.editLocked=!S.editLocked;if(!S.editLocked)S.manualEditDays=editDays(S.episodes,S.editDaysPerEpisode);save();render()};let rs=app.querySelector('[data-reset]');if(rs)rs.onclick=()=>{localStorage.removeItem(KEY);S=fresh();render()};let cp=app.querySelector('[data-copy]');if(cp)cp.onclick=()=>{let C=calc();navigator.clipboard.writeText(['Planuf Productions Budget Summary','Project: '+S.projectName,'Episodes: '+S.episodes,'Shoot days: '+C.sc.shoot,'Edit days: '+C.sc.edit,'Total required spend: '+£(C.total)].join('\n'))}}
render();
})();
