const KEY='rotaAppUnifiedV2';
const $=id=>document.getElementById(id);
const clean=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=p=>p+'_'+Math.random().toString(36).slice(2,9);
const today=()=>new Date().toISOString().slice(0,10);
const nowISO=()=>new Date().toISOString();
const timeNow=()=>new Date().toTimeString().slice(0,5);
const dlab=d=>new Date(d+'T12:00:00').toLocaleDateString('en-GB',{weekday:'short',day:'numeric',month:'short'});
const mins=t=>{let [h,m]=String(t||'00:00').split(':').map(Number);return h*60+m};
const dur=(a,b)=>{let m=mins(b)-mins(a);return m<0?m+1440:m};
const hrs=m=>Math.round(m/60*100)/100;
const managers=['Vikki Fox','Chip Butt','Rhiannon Green'];
const names=['Ali','Andrew','April Hobday','April Hood','Ben','Ben McManus','Chan','Charlie','Chip Butt','Darcey Warwick','Ellie','Fleur','Frederick Lees','Hayden Smith','Jake','Jamie Cox','Jess Keddie','Katie','Logan','Maisie Morris','Mandi','Marc Pearmain','Meg','Megan','Paul Davis','Rhiannon Green','Ryan Thompson','Sharon Hiatt','Skye','Sophia Vassalos','Tom Mills','Vikki Fox','Zoe'];
const permLabels={viewPeople:'View people list',manageUsers:'Manage user profiles',manageRota:'Create/edit rota',viewAllTimesheets:'View all timesheets',manageTimesheets:'Manage timesheets',viewAllLeave:'View all leave',manageLeave:'Approve/edit leave',editLeaveBalances:'Edit leave balances',viewReports:'View reports',managePermissionSets:'Edit permission sets',viewOwnProfile:'View own profile',editOwnPersonal:'Edit own personal details',viewOwnShifts:'View own shifts',clockIn:'Clock in/out',requestLeave:'Request leave',viewOwnLeave:'View own leave',viewOwnTimesheets:'View own timesheets',viewOwnAvailability:'View own availability',editOwnAvailability:'Edit own availability'};
const adminPerms=Object.fromEntries(Object.keys(permLabels).map(k=>[k,true]));
const staffPerms={viewPeople:false,manageUsers:false,manageRota:false,viewAllTimesheets:false,manageTimesheets:false,viewAllLeave:false,manageLeave:false,editLeaveBalances:false,viewReports:false,managePermissionSets:false,viewOwnProfile:true,editOwnPersonal:true,viewOwnShifts:true,clockIn:true,requestLeave:true,viewOwnLeave:true,viewOwnTimesheets:true,viewOwnAvailability:true,editOwnAvailability:true};
function idFromName(n){return 'u_'+n.toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'')}
function splitName(n){let p=n.trim().split(/\s+/);return{firstName:p[0]||'',lastName:p.slice(1).join(' ')}}
function initials(n){let p=n.split(' ');return (p[0]?.[0]||'')+(p[1]?.[0]||'')}
function makeUser(n){let admin=managers.includes(n),sp=splitName(n);return{id:idFromName(n),firstName:sp.firstName,lastName:sp.lastName,name:n,nickname:sp.firstName,email:n==='Chip Butt'?'jameschipbutt@hotmail.com':'',mobile:'',dob:'',address:'',wage:0,jobArea:admin?'Office':'FOH',pronouns:'',permissionSetId:admin?'admin':'staff',role:admin?'admin':'staff',accountStatus:admin?'confirmed':(n==='Paul Davis'?'invited':'no_email'),inviteSentAt:n==='Paul Davis'?nowISO():null,confirmedAt:admin?nowISO():null,newShiftEmail:true,upcomingShiftAlerts:true,holidayAllowanceDays:28,holidayCarriedDays:0,holidayAdjustmentDays:0,availability:{mon:true,tue:true,wed:true,thu:true,fri:true,sat:false,sun:false}}}
const defaultPermissionSets={admin:{id:'admin',name:'Admin',description:'Full access to view and edit everything.',permissions:adminPerms},staff:{id:'staff',name:'Staff',description:'Can view own rota/profile/timesheets/leave, clock in, request leave, and edit allowed personal details.',permissions:staffPerms}};
const seed={currentUserId:idFromName('Chip Butt'),view:'rota',profileUserId:null,profilePanel:'home',leavePanel:'requests',adminPanel:'shift',sections:['Kitchen','FOH','Office','WFH','Housekeeping','KP','Kitchen PotWash'],permissionSets:defaultPermissionSets,users:names.map(makeUser),shifts:[],logs:{},leaveRequests:[],alerts:[]};
function load(){let raw=localStorage.getItem(KEY)||localStorage.getItem('rotaAppUnified');let s;try{s=JSON.parse(raw||'null')}catch(e){};if(!s){s=structuredClone(seed);s.shifts=[{id:uid('s'),userId:idFromName('Ali'),section:'Kitchen PotWash',date:today(),start:'10:00',end:'21:00',notes:'Kitchen PotWash, The Stag At Red Hill'},{id:uid('s'),userId:idFromName('Marc Pearmain'),section:'Kitchen',date:today(),start:'09:00',end:'15:00',notes:'Kitchen, The Stag At Red Hill'}];s.leaveRequests=[{id:uid('l'),userId:idFromName('Ali'),startDate:'2026-08-13',endDate:'2026-08-14',type:'paid',status:'approved',days:2,hours:10},{id:uid('l'),userId:idFromName('Ali'),startDate:'2026-08-10',endDate:'2026-08-10',type:'paid',status:'approved',days:1,hours:6}];}
s.permissionSets={...structuredClone(defaultPermissionSets),...(s.permissionSets||{})};s.users=(s.users||[]).map(u=>{let n=u.name||[u.firstName,u.lastName].filter(Boolean).join(' ')||'Unknown',base=makeUser(n);let merged={...base,...u};if(!merged.firstName||!merged.lastName){let sp=splitName(merged.name);merged.firstName=merged.firstName||sp.firstName;merged.lastName=merged.lastName||sp.lastName}merged.name=[merged.firstName,merged.lastName].filter(Boolean).join(' ')||merged.name;merged.permissionSetId=merged.permissionSetId||(merged.role==='admin'?'admin':'staff');merged.newShiftEmail=true;merged.upcomingShiftAlerts=merged.upcomingShiftAlerts!==false;return merged});names.forEach(n=>{if(!s.users.some(u=>u.name.toLowerCase()===n.toLowerCase()))s.users.push(makeUser(n))});s.sections=s.sections||seed.sections;s.shifts=s.shifts||[];s.logs=s.logs||{};s.alerts=s.alerts||[];s.leaveRequests=s.leaveRequests||[];if(!s.currentUserId||!s.users.find(u=>u.id===s.currentUserId))s.currentUserId=idFromName('Chip Butt');localStorage.setItem(KEY,JSON.stringify(s));return s}
let state=load(),weekStart=monday(new Date()),swipeX=null;
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function me(){return state.users.find(u=>u.id===state.currentUserId)||state.users[0]}
function permsFor(u=me()){return state.permissionSets[u.permissionSetId]?.permissions||staffPerms}
function can(k,u=me()){return !!permsFor(u)[k]}
function isAdmin(){return can('manageRota')||can('manageUsers')||can('managePermissionSets')}
function canEditUser(target,field){let self=target.id===me().id;if(can('manageUsers'))return true;if(!self||!can('editOwnPersonal'))return false;return ['nickname','dob','address','mobile','pronouns','upcomingShiftAlerts','password'].includes(field)}
function setView(v){state.view=v;save();render()}
function monday(d){d=new Date(d);let n=(d.getDay()+6)%7;d.setHours(0,0,0,0);d.setDate(d.getDate()-n);return d}
function plus(d,n){d=new Date(d);d.setDate(d.getDate()+n);return d}
function iso(d){return d.toISOString().slice(0,10)}
function log(sid){return state.logs[sid]||{in:null,out:null,breaks:[]}}
function activeShift(){return state.shifts.find(s=>s.userId===state.currentUserId&&log(s.id).in&&!log(s.id).out)}
function shell(inner){let nav=[`<button class="tab ${state.view==='rota'?'active':''}" onclick="setView('rota')">Schedule</button>`];if(can('clockIn'))nav.push(`<button class="tab ${state.view==='clock'?'active':''}" onclick="setView('clock')">Clock In</button>`);if(can('viewPeople')||can('manageUsers'))nav.push(`<button class="tab ${state.view==='people'?'active':''}" onclick="setView('people')">People</button>`);if(isAdmin())nav.push(`<button class="tab ${state.view==='admin'?'active':''}" onclick="setView('admin')">Admin</button>`);if(can('viewAllTimesheets'))nav.push(`<button class="tab ${state.view==='timesheets'?'active':''}" onclick="setView('timesheets')">Timesheets</button>`);$('app').innerHTML=`<header class="topbar"><div><h1>Rota App</h1><p>${clean(me().name)} · ${clean(state.permissionSets[me().permissionSetId]?.name||'Staff')}</p></div><div class="topActions"><select id="currentUserSelect">${state.users.map(u=>`<option value="${u.id}" ${u.id===state.currentUserId?'selected':''}>${clean(u.nickname)} (${clean(state.permissionSets[u.permissionSetId]?.name||'Staff')})</option>`).join('')}</select></div></header><nav class="tabs">${nav.join('')}</nav><main>${inner}</main>`;$('currentUserSelect').onchange=e=>{state.currentUserId=e.target.value;save();render()}}
function render(){if(state.view==='clock')renderClock();else if(state.view==='people')renderPeople();else if(state.view==='profile')renderProfile();else if(state.view==='profileEdit')renderProfileEdit();else if(state.view==='admin')renderAdmin();else if(state.view==='timesheets')renderTimesheets();else renderRota()}
function renderRota(){let days=[0,1,2,3,4,5,6].map(n=>plus(weekStart,n));let body=`<div class="toolbar"><button class="secondary" onclick="weekStart=plus(weekStart,-7);renderRota()">Previous</button><strong>${dlab(iso(days[0]))} – ${dlab(iso(days[6]))}</strong><button class="secondary" onclick="weekStart=plus(weekStart,7);renderRota()">Next</button></div><div id="rotaGrid" class="rotaGrid fitWeek"><div class="gridCell gridHead areaHead">Area</div>${days.map(d=>`<div class="gridCell gridHead">${dlab(iso(d)).replace(' ','<br>')}</div>`).join('')}${state.sections.map(sec=>`<div class="gridCell sectionHead">${clean(sec)}</div>${days.map(d=>{let ds=iso(d),ss=state.shifts.filter(s=>s.section===sec&&s.date===ds);return `<div class="gridCell rotaDayCell">${ss.map(shiftCard).join('')||'<span class="muted">—</span>'}${can('manageRota')?`<button class="cellAddShift" onclick="openShiftModal('', '${ds}', '${clean(sec)}')">+</button>`:''}</div>`}).join('')}`).join('')}</div><p class="muted swipeHint">Monday–Sunday rota. Swipe left or right to change week.</p>`;shell(body);let g=$('rotaGrid');g.addEventListener('touchstart',e=>swipeX=e.touches[0].clientX,{passive:true});g.addEventListener('touchend',e=>{let dx=e.changedTouches[0].clientX-swipeX;if(Math.abs(dx)>45){weekStart=plus(weekStart,dx<0?7:-7);renderRota()}},{passive:true})}
function shiftCard(s){let u=state.users.find(x=>x.id===s.userId)||{};let tap=can('manageRota')?`onclick="openShiftModal('${s.id}')"`:'';return `<div class="shiftCard ${s.unscheduled?'unscheduled':''} ${can('manageRota')?'editableShift':''}" ${tap}><strong>${clean(u.nickname||'Unknown')}</strong><span>${s.start}-${s.end}</span><small>${s.unscheduled?'Unscheduled ':''}${hrs(dur(s.start,s.end))} hrs</small></div>`}
function openShiftModal(sid='',date='',section=''){if(!can('manageRota'))return;let existing=state.shifts.find(s=>s.id===sid);let s=existing||{id:'',userId:state.users.find(u=>u.permissionSetId!=='admin')?.id||state.users[0].id,section:section||state.sections[0],date:date||today(),start:'09:00',end:'17:00',notes:''};document.querySelector('.modalBackdrop')?.remove();let div=document.createElement('div');div.className='modalBackdrop';div.innerHTML=`<div class="shiftModal"><button class="modalClose" onclick="closeShiftModal()">×</button><h2>${existing?'Edit shift':'Add shift'}</h2><form onsubmit="saveShiftModal(event,'${sid}')" class="formGrid"><label>Staff<select id="modalShiftUser">${state.users.map(u=>`<option value="${u.id}" ${u.id===s.userId?'selected':''}>${clean(u.name)}</option>`).join('')}</select></label><label>Section<select id="modalShiftSection">${state.sections.map(x=>`<option ${x===s.section?'selected':''}>${clean(x)}</option>`).join('')}</select></label><label>Date<input id="modalShiftDate" type="date" value="${s.date}"></label><label>Start<input id="modalShiftStart" type="time" value="${s.start}"></label><label>End<input id="modalShiftEnd" type="time" value="${s.end}"></label><label class="full">Notes<textarea id="modalShiftNotes">${clean(s.notes||'')}</textarea></label><div class="full formActions"><button>Save shift</button>${existing?`<button type="button" class="danger" onclick="deleteShiftFromModal('${sid}')">Delete</button>`:''}</div></form></div>`;document.body.appendChild(div)}
function closeShiftModal(){document.querySelector('.modalBackdrop')?.remove()}
function saveShiftModal(e,sid){e.preventDefault();let existing=state.shifts.find(s=>s.id===sid);let data={id:sid||uid('s'),userId:$('modalShiftUser').value,section:$('modalShiftSection').value,date:$('modalShiftDate').value,start:$('modalShiftStart').value,end:$('modalShiftEnd').value,notes:$('modalShiftNotes').value,unscheduled:existing?.unscheduled||false};if(existing)Object.assign(existing,data);else{state.shifts.push(data);queueNewShiftAlert(data)}save();closeShiftModal();renderRota()}
function deleteShiftFromModal(sid){if(!confirm('Delete this shift?'))return;state.shifts=state.shifts.filter(s=>s.id!==sid);delete state.logs[sid];save();closeShiftModal();renderRota()}
function renderClock(){let ss=state.shifts.filter(s=>s.userId===state.currentUserId&&s.date===today());let a=activeShift();shell(`<section class="panel"><h2>Clock In</h2><div class="workCard"><h3>Start unscheduled shift</h3><p class="muted">Use this if no shift has been added for you.</p><label>Section<select id="unscheduledSection">${state.sections.map(s=>`<option>${clean(s)}</option>`).join('')}</select></label><label>Note<input id="unscheduledNote" placeholder="Optional duty note"></label><button ${a?'disabled':''} onclick="startUnscheduledShift()">Clock in without scheduled shift</button></div>${ss.map(s=>{let l=log(s.id),on=l.in&&!l.out;return `<div class="workCard"><h3>${clean(s.section)}</h3><p>${s.start} – ${s.end}</p><p class="muted">${clean(s.notes||'')}</p><span class="statusBadge ${on?'live':''}">${on?'Clocked in':l.out?'Clocked out':'Ready'}</span><div class="breakControls"><button ${l.in?'disabled':''} onclick="clockIn('${s.id}')">Clock in</button><button ${!on?'disabled':''} onclick="clockOut('${s.id}')">Clock out</button><button class="secondary" ${!on?'disabled':''} onclick="startBreak('${s.id}',false)">Unpaid break</button><button class="secondary" ${!on?'disabled':''} onclick="startBreak('${s.id}',true)">Paid break</button></div></div>`}).join('')||'<p class="muted">No scheduled shifts today.</p>'}</section>`)}
function renderPeople(){if(!can('viewPeople')&&!can('manageUsers'))return setView('rota');shell(`<section class="panel peoplePanel"><div class="sectionHeader"><h2>People</h2>${can('manageUsers')?'<button onclick="newUser()">+</button>':''}</div><input id="peopleSearch" placeholder="Search ${state.users.length} people"><div id="peopleList"></div></section>`);let draw=()=>{let q=$('peopleSearch').value.toLowerCase();$('peopleList').innerHTML=state.users.filter(u=>u.name.toLowerCase().includes(q)).sort((a,b)=>a.name.localeCompare(b.name)).map(u=>`<div class="personRow" onclick="openProfile('${u.id}')"><span class="avatarText">${initials(u.name)}</span><div><strong>${clean(u.name)}</strong><p>${statusLine(u)}</p></div><span class="chev">›</span></div>`).join('')};$('peopleSearch').oninput=draw;draw()}
function statusLine(u){let live=state.shifts.find(s=>s.userId===u.id&&log(s.id).in&&!log(s.id).out),up=state.shifts.find(s=>s.userId===u.id&&s.date>=today());return live?'On shift':up?'Upcoming shift':u.accountStatus==='invited'?'Invited':''}
function openProfile(uid){state.profileUserId=uid;state.profilePanel='home';state.leavePanel='requests';state.view='profile';save();render()}
function profileUser(){return state.users.find(u=>u.id===state.profileUserId)||me()}
function canViewProfile(u){return can('manageUsers')||can('viewPeople')||u.id===me().id&&can('viewOwnProfile')}
function renderProfile(){let u=profileUser();if(!canViewProfile(u))return setView('rota');let sub=state.profilePanel;if(sub==='shifts')return renderProfileShifts(u);if(sub==='timesheets')return renderProfileTimesheets(u);if(sub==='leave')return renderProfileLeave(u);if(sub==='availability')return renderProfileAvailability(u);let next=state.shifts.find(s=>s.userId===u.id&&s.date>=today());shell(`<section class="profilePage"><div class="profileTop"><button class="roundBtn" onclick="setView('people')">‹</button><h2>${clean(u.nickname||u.name)}</h2>${can('manageUsers')||u.id===me().id&&can('editOwnPersonal')?`<button class="secondary" onclick="openProfileEdit('${u.id}')">Edit Profile</button>`:''}</div><div class="profileHero"><span class="avatarText big">${initials(u.name)}</span><div>${next?`<p>Starting at ${clean(next.section)}</p><h2>${next.start} – ${next.end}</h2>`:'<p>No upcoming shift</p>'}</div></div><div class="quickActions"><button class="secondary">Find replacement</button>${u.id===me().id&&can('clockIn')||can('manageUsers')?`<button onclick="state.currentUserId='${u.id}';save();setView('clock')">Start shift</button>`:''}</div><div class="profileLinks"><button onclick="profilePanel('shifts')">Upcoming shifts <span>›</span></button><button onclick="profilePanel('timesheets')">Timesheets <span>›</span></button><button onclick="profilePanel('leave')">Leave <span>›</span></button><button onclick="profilePanel('availability')">Availability <span>›</span></button></div></section>`)}
function profilePanel(p){state.profilePanel=p;save();render()}
function profileHeader(u,title){return `<div class="profileTop"><button class="roundBtn" onclick="profilePanel('home')">‹</button><h2>${title}</h2><span></span></div>`}
function renderProfileShifts(u){let ss=state.shifts.filter(s=>s.userId===u.id).sort((a,b)=>a.date.localeCompare(b.date));shell(`<section class="profilePage">${profileHeader(u,'Upcoming shifts')}<div class="panel">${ss.map(s=>`<div class="listItem"><strong>${dlab(s.date)}</strong><p>${s.start} – ${s.end}</p><p class="muted">${clean(s.section)}, The Stag At Red Hill</p></div>`).join('')||'<p class="muted">No shifts.</p>'}</div></section>`)}
function renderProfileTimesheets(u){let ss=state.shifts.filter(s=>s.userId===u.id);shell(`<section class="profilePage">${profileHeader(u,'Timesheet')}<div class="panel">${ss.map(s=>`<div class="listItem"><strong>${dlab(s.date)}</strong><p>${s.start} – ${s.end} · 0m break</p><p class="muted">${clean(s.section)}, The Stag At Red Hill</p><span class="statusBadge">Pending</span></div>`).join('')||'<p class="muted">No timesheets.</p>'}</div></section>`)}
function usedLeaveDays(u){return state.leaveRequests.filter(r=>r.userId===u.id&&r.type==='paid'&&r.status==='approved').reduce((t,r)=>t+Number(r.days||0),0)}
function leaveBalance(u){let allowance=Number(u.holidayAllowanceDays||0),carried=Number(u.holidayCarriedDays||0),adjust=Number(u.holidayAdjustmentDays||0),used=usedLeaveDays(u),total=allowance+carried+adjust;return{allowance,carried,adjust,used,total,remaining:total-used}}
function renderProfileLeave(u){let rs=state.leaveRequests.filter(r=>r.userId===u.id),b=leaveBalance(u);shell(`<section class="profilePage">${profileHeader(u,'Leave Requests')}<div class="segTabs"><button class="${state.leavePanel!=='balances'?'active':''}" onclick="state.leavePanel='requests';save();render()">Requests</button><button class="${state.leavePanel==='balances'?'active':''}" onclick="state.leavePanel='balances';save();render()">Balances</button></div>${state.leavePanel==='balances'?`<div class="panel"><h2>Holiday Balance</h2><div class="balanceGrid"><div><strong>${b.remaining}</strong><span>Days remaining</span></div><div><strong>${b.used}</strong><span>Days used</span></div><div><strong>${b.total}</strong><span>Total allowance</span></div></div><div class="listItem"><p>Annual allowance: ${b.allowance} days</p><p>Carried over: ${b.carried} days</p><p>Manual adjustment: ${b.adjust} days</p></div>${can('editLeaveBalances')?`<button onclick="openProfileEdit('${u.id}','leave')">Edit leave balance</button>`:''}</div>`:`<div class="panel">${rs.map(r=>`<div class="listItem"><strong>${dlab(r.startDate)}</strong><p>${dlab(r.endDate)}</p><p class="linkish">${r.type==='paid'?'UK Holiday Policy (Full-Time)':'Unpaid Time Off'}</p><p class="muted">${r.days} days (${r.hours||r.days*8} hours)</p><span class="approved">${r.status}</span></div>`).join('')||'<p class="muted">No leave requests.</p>'}</div>`}</section>`)}
function renderProfileAvailability(u){let a=u.availability||{};let days=[['mon','Monday'],['tue','Tuesday'],['wed','Wednesday'],['thu','Thursday'],['fri','Friday'],['sat','Saturday'],['sun','Sunday']];shell(`<section class="profilePage">${profileHeader(u,'Availability')}<div class="panel"><h2>Recurring</h2>${days.map(([k,l])=>`<div class="availRow"><div><strong>${l}</strong><p>All day</p><p>Every week</p></div><span class="avail ${a[k]?'yes':'no'}">${a[k]?'Available':'Unavailable'}</span></div>`).join('')}<p class="muted">Last modified 28 Jan 2026</p></div></section>`)}
function openProfileEdit(uid,focus=''){state.profileUserId=uid;state.profilePanel=focus||'home';state.view='profileEdit';save();render()}
function field(name,label,type='text',adminOnly=false){let u=profileUser(),editable=canEditUser(u,name)&&(!adminOnly||can('manageUsers'));let val=u[name]??'';return `<label>${label}<input id="edit_${name}" type="${type}" value="${clean(val)}" ${editable?'':'disabled'}></label>`}
function renderProfileEdit(){let u=profileUser(),adminEdit=can('manageUsers'),self=u.id===me().id;if(!adminEdit&&!(self&&can('editOwnPersonal')))return setView('profile');shell(`<section class="profilePage"><div class="profileTop"><button class="roundBtn" onclick="setView('profile')">‹</button><h2>Edit Profile</h2><span></span></div><form class="panel formGrid editProfileForm" onsubmit="saveProfileEdit(event)"><h2 class="full">Personal details</h2>${field('firstName','First name','text',true)}${field('lastName','Last name','text',true)}${field('nickname','Nickname')}${field('dob','Date of birth','date')}${field('address','Address')}${field('mobile','Mobile number','tel')}${field('email','Email','email',true)}${field('pronouns','Pronouns')}<h2 class="full">Employment</h2>${field('wage','Pay rate (£)','number',true)}<label>Job area<select id="edit_jobArea" ${adminEdit?'':'disabled'}>${state.sections.map(s=>`<option ${u.jobArea===s?'selected':''}>${clean(s)}</option>`).join('')}</select></label><label>Permission set<select id="edit_permissionSetId" ${adminEdit?'':'disabled'}>${Object.values(state.permissionSets).map(p=>`<option value="${p.id}" ${u.permissionSetId===p.id?'selected':''}>${clean(p.name)}</option>`).join('')}</select></label><h2 class="full">Leave balance</h2>${field('holidayAllowanceDays','Annual allowance days','number',true)}${field('holidayCarriedDays','Carried over days','number',true)}${field('holidayAdjustmentDays','Manual adjustment days','number',true)}<h2 class="full">User settings</h2><label class="checkLabel">Upcoming shift alerts<input id="edit_upcomingShiftAlerts" type="checkbox" ${u.upcomingShiftAlerts?'checked':''} ${canEditUser(u,'upcomingShiftAlerts')?'':'disabled'}></label><label class="full">Update password<input id="edit_password" type="password" placeholder="New password placeholder" ${canEditUser(u,'password')?'':'disabled'}></label><p class="muted full">First name, last name, email, pay rate, permission set and leave balance are admin-controlled fields.</p><div class="full formActions"><button>Save profile</button><button type="button" class="secondary" onclick="setView('profile')">Cancel</button></div></form></section>`)}
function saveProfileEdit(e){e.preventDefault();let u=profileUser(),adminEdit=can('manageUsers'),set=(k,v)=>{if(canEditUser(u,k)||adminEdit)u[k]=v};if(adminEdit){u.firstName=$('edit_firstName').value.trim();u.lastName=$('edit_lastName').value.trim();u.name=[u.firstName,u.lastName].filter(Boolean).join(' ');u.email=$('edit_email').value.trim();u.wage=Number($('edit_wage').value||0);u.jobArea=$('edit_jobArea').value;u.permissionSetId=$('edit_permissionSetId').value;u.holidayAllowanceDays=Number($('edit_holidayAllowanceDays').value||0);u.holidayCarriedDays=Number($('edit_holidayCarriedDays').value||0);u.holidayAdjustmentDays=Number($('edit_holidayAdjustmentDays').value||0)}set('nickname',$('edit_nickname').value.trim());set('dob',$('edit_dob').value);set('address',$('edit_address').value.trim());set('mobile',$('edit_mobile').value.trim());set('pronouns',$('edit_pronouns').value.trim());set('upcomingShiftAlerts',$('edit_upcomingShiftAlerts').checked);if(u.email&&u.accountStatus==='no_email')u.accountStatus='uninvited';save();state.view='profile';save();render()}
function renderAdmin(){shell(`<section class="panel"><div class="adminTabs"><button class="adminTab ${state.adminPanel==='shift'?'active':''}" onclick="adminPanel('shift')">Add / edit shift</button><button class="adminTab ${state.adminPanel==='sections'?'active':''}" onclick="adminPanel('sections')">Sections</button><button class="adminTab ${state.adminPanel==='users'?'active':''}" onclick="adminPanel('users')">Users</button><button class="adminTab ${state.adminPanel==='permissions'?'active':''}" onclick="adminPanel('permissions')">Permissions</button></div><div id="adminInner"></div></section>`);drawAdmin()}
function adminPanel(p){state.adminPanel=p;save();drawAdmin()}
function drawAdmin(){let el=$('adminInner');if(state.adminPanel==='sections')el.innerHTML=`<h2>Sections</h2><form class="rowForm" onsubmit="addSection(event)"><input id="newSectionName" placeholder="New section"><button>Add section</button></form><div class="sectionList">${state.sections.map(s=>`<div class="sectionRow"><span>${clean(s)}</span><button class="iconBtn danger" onclick="removeSection('${clean(s)}')">🗑</button></div>`).join('')}</div>`;else if(state.adminPanel==='permissions')el.innerHTML=renderPermissionSets();else if(state.adminPanel==='users')el.innerHTML=`<h2>Users</h2><div class="tableWrap"><table><tr><th>Name</th><th>Email/mobile</th><th>Permission</th><th>Status</th><th></th></tr>${state.users.map(u=>`<tr><td><button class="linkBtn" onclick="openProfile('${u.id}')">${clean(u.name)}</button><br><span class="muted">${clean(u.jobArea||'')}</span></td><td>${clean(u.email||'No email')}<br><span class="muted">${clean(u.mobile||'No mobile')}</span></td><td>${clean(state.permissionSets[u.permissionSetId]?.name||'Staff')}</td><td>${clean(userStatus(u))}</td><td><button class="small secondary" onclick="openProfileEdit('${u.id}')">Edit</button>${u.email&&u.accountStatus!=='confirmed'?`<button class="small" onclick="inviteUser('${u.id}')">Invite User</button>`:''}</td></tr>`).join('')}</table></div>`;else el.innerHTML=`<h2>Add shift</h2><form class="formGrid" onsubmit="saveShift(event)"><label>Staff<select id="shiftUser">${state.users.map(u=>`<option value="${u.id}">${clean(u.name)}</option>`).join('')}</select></label><label>Section<select id="shiftSection">${state.sections.map(s=>`<option>${clean(s)}</option>`).join('')}</select></label><label>Date<input id="shiftDate" type="date" value="${today()}"></label><label>Start<input id="shiftStart" type="time" value="09:00"></label><label>End<input id="shiftEnd" type="time" value="17:00"></label><label class="full">Notes<textarea id="shiftNotes"></textarea></label><button>Save shift</button></form>`}
function renderPermissionSets(){if(!can('managePermissionSets'))return '<p class="muted">You do not have permission to edit permission sets.</p>';return `<h2>Permission sets</h2><p class="muted">These are base permission sets assigned to users. Editing Staff changes what staff can see and edit.</p>${Object.values(state.permissionSets).map(ps=>`<div class="permissionSet"><h3>${clean(ps.name)}</h3><p class="muted">${clean(ps.description||'')}</p><div class="permissionGrid">${Object.entries(permLabels).map(([k,label])=>`<label class="checkLabel">${clean(label)}<input type="checkbox" data-set="${ps.id}" data-perm="${k}" ${ps.permissions[k]?'checked':''} ${ps.id==='admin'&&k==='managePermissionSets'?'disabled':''}></label>`).join('')}</div></div>`).join('')}<button onclick="savePermissionSets()">Save permission sets</button>`}
function savePermissionSets(){document.querySelectorAll('[data-set][data-perm]').forEach(cb=>{state.permissionSets[cb.dataset.set].permissions[cb.dataset.perm]=cb.checked});state.permissionSets.admin.permissions.managePermissionSets=true;save();renderAdmin()}
function userStatus(u){return u.accountStatus==='confirmed'?'Confirmed':u.accountStatus==='invited'?'Invited':u.email?'Needs invite':'No email'}
function renderTimesheets(){shell(`<section class="panel"><h2>Timesheets</h2><div class="tableWrap"><table><tr><th>Date</th><th>User</th><th>Shift</th><th>Payable</th></tr>${state.shifts.map(s=>{let u=state.users.find(x=>x.id===s.userId)||{};return `<tr><td>${s.date}</td><td>${clean(u.name)}</td><td>${s.start}-${s.end} ${clean(s.section)}</td><td>${hrs(dur(s.start,s.end))} hrs</td></tr>`}).join('')}</table></div></section>`)}
function startUnscheduledShift(){if(activeShift())return alert('You are already clocked in.');let sid=uid('s'),t=timeNow(),s={id:sid,userId:state.currentUserId,section:$('unscheduledSection').value,date:today(),start:t,end:t,notes:$('unscheduledNote').value||'Unscheduled shift',unscheduled:true};state.shifts.push(s);state.logs[sid]={in:nowISO(),out:null,breaks:[]};save();renderClock()}
function clockIn(sid){if(activeShift())return alert('You are already clocked in.');state.logs[sid]={...log(sid),in:nowISO(),out:null};save();renderClock()}
function clockOut(sid){let l=log(sid);l.out=nowISO();let s=state.shifts.find(x=>x.id===sid);if(s?.unscheduled)s.end=timeNow();state.logs[sid]=l;save();renderClock()}
function startBreak(sid,paid){let l=log(sid);l.breaks.push({start:nowISO(),paid});state.logs[sid]=l;save();renderClock()}
function saveShift(e){e.preventDefault();let s={id:uid('s'),userId:$('shiftUser').value,section:$('shiftSection').value,date:$('shiftDate').value,start:$('shiftStart').value,end:$('shiftEnd').value,notes:$('shiftNotes').value};state.shifts.push(s);queueNewShiftAlert(s);save();renderAdmin()}
function queueNewShiftAlert(s){let u=state.users.find(x=>x.id===s.userId);if(u?.email)state.alerts.push({id:uid('alert'),type:'new_shift_email',userId:u.id,email:u.email,shiftId:s.id,createdAt:nowISO(),fixedOn:true})}
function addSection(e){e.preventDefault();let n=$('newSectionName').value.trim();if(n&&!state.sections.includes(n))state.sections.push(n);save();drawAdmin()}
function removeSection(s){if(state.shifts.some(x=>x.section===s))return alert('Move or delete shifts in this section first.');state.sections=state.sections.filter(x=>x!==s);save();drawAdmin()}
function inviteUser(uid){let u=state.users.find(x=>x.id===uid);if(!u?.email)return alert('Add an email before inviting.');u.accountStatus='invited';u.inviteSentAt=nowISO();state.alerts.push({id:uid('alert'),type:'account_invite_email',userId:u.id,email:u.email,createdAt:nowISO()});save();drawAdmin();alert('Invite queued. Real email sending needs backend email service.')}
function newUser(){let n=prompt('User name');if(!n)return;let u=makeUser(n);state.users.push(u);save();renderPeople()}
window.setView=setView;window.openProfile=openProfile;window.profilePanel=profilePanel;window.adminPanel=adminPanel;window.startUnscheduledShift=startUnscheduledShift;window.clockIn=clockIn;window.clockOut=clockOut;window.startBreak=startBreak;window.saveShift=saveShift;window.addSection=addSection;window.removeSection=removeSection;window.inviteUser=inviteUser;window.newUser=newUser;window.openShiftModal=openShiftModal;window.closeShiftModal=closeShiftModal;window.saveShiftModal=saveShiftModal;window.deleteShiftFromModal=deleteShiftFromModal;window.openProfileEdit=openProfileEdit;window.saveProfileEdit=saveProfileEdit;window.savePermissionSets=savePermissionSets;
render();